version: '3.8'

services:
  main_server:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    command: python3 main.py
    ports:
      - "5000:5000"
    networks:
      - app_network

  models_workflow:
    image: python:3.10
    working_dir: /app/Models_workflow
    volumes:
      - .:/app
    command: python3 app.py
    ports:
      - "5002:5002"
    networks:
      - app_network

  speech_gen:
    image: python:3.10
    working_dir: /app/Models_workflow/speech_gen
    volumes:
      - .:/app
    command: python3 app.py
    ports:
      - "5001:5001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
