// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATD8pv2fcgJ6ipv5e1dLFhu___Vbedi5Y',
    appId: '1:847979728741:web:c9af036b7d08d3b50d1b8c',
    messagingSenderId: '847979728741',
    projectId: 'boost-app-f9dc1',
    authDomain: 'boost-app-f9dc1.firebaseapp.com',
    storageBucket: 'boost-app-f9dc1.firebasestorage.app',
    measurementId: 'G-J4GTG12GZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNHu7XBrVAhi9S7lAZC1o4hXA2eFheDY',
    appId: '1:847979728741:android:ac7a01ba7abe08a90d1b8c',
    messagingSenderId: '847979728741',
    projectId: 'boost-app-f9dc1',
    storageBucket: 'boost-app-f9dc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoP97bswrY1ysK3EmVxtpLYke3T8PphI',
    appId: '1:847979728741:ios:83f70b8c9764aafa0d1b8c',
    messagingSenderId: '847979728741',
    projectId: 'boost-app-f9dc1',
    storageBucket: 'boost-app-f9dc1.firebasestorage.app',
    iosBundleId: 'com.boostapp.boostApp',
  );
}
